// Datos de docs/ETAPAS OBRA: 10 etapas de construccion con sus subetapas,
// mas el mapeo contra los capitulos del presupuesto (docs/ETAPAS OBRA/MAPEO_CAPITULOS_PRESUPUESTO.md).
window.DATOS_ETAPAS = {
  fuente: 'pages/PROYECTOS/Plantilla Modelo/ETAPAS OBRA',
  etapasColor: {
    negra: { nombre: 'Obra Negra', color: '#2b2d34' },
    gris: { nombre: 'Obra Gris', color: '#6b7280' },
    blanca: { nombre: 'Obra Blanca', color: '#c9a24b' },
  },
  etapas: [
    { n: 1, carpeta: '01_PRELIMINARES', nombre: 'Preliminares', etapa: 'negra',
      subetapas: ['Limpieza', 'Descapote', 'Nivelación', 'Recebado y Compactación', 'Replanteo', 'Cerramiento Provisional', 'Campamento', 'Instalaciones Provisionales'] },
    { n: 2, carpeta: '02_EXCAVACIONES', nombre: 'Excavaciones', etapa: 'negra',
      subetapas: ['Excavación Zapatas', 'Excavación Vigas Cimentación', 'Retiro Material'] },
    { n: 3, carpeta: '03_CIMENTACION', nombre: 'Cimentación', etapa: 'negra',
      subetapas: ['Zapatas', 'Vigas Cimentación', 'Placa Contrapiso'] },
    { n: 4, carpeta: '04_ESTRUCTURA', nombre: 'Estructura', etapa: 'negra',
      subetapas: ['Flejes Columnas Primer Piso', 'Flejes Entrepiso 1-2', 'Flejes Columnas Entrepiso 2', 'Flejes Entrepiso 2-3', 'Flejes Columnas Piso 3', 'Flejes Vigas Cubierta', 'Flejes Cubierta'] },
    { n: 5, carpeta: '05_MAMPOSTERIA', nombre: 'Mampostería', etapa: 'gris',
      subetapas: ['Muros Exteriores', 'Muros Interiores', 'Dinteles y Antepechos'] },
    { n: 6, carpeta: '06_INSTALACIONES', nombre: 'Instalaciones', etapa: 'gris',
      subetapas: ['Hidráulicas', 'Sanitarias', 'Eléctricas', 'Especiales'] },
    { n: 7, carpeta: '07_CUBIERTA', nombre: 'Cubierta', etapa: 'negra',
      subetapas: ['Estructura', 'Impermeabilización', 'Acabado'] },
    { n: 8, carpeta: '08_ACABADOS', nombre: 'Acabados', etapa: 'blanca',
      subetapas: ['Pañetes', 'Pisos', 'Enchapes', 'Pintura', 'Carpintería y Herrería', 'Estuco', 'Aparatos Hidrosanitarios', 'Mueble Cocina', 'Armarios'] },
    { n: 9, carpeta: '09_EXTERIORES', nombre: 'Exteriores', etapa: 'blanca',
      subetapas: ['Fachadas', 'Andenes', 'Zonas Exteriores', 'Cerramiento Definitivo'] },
    { n: 10, carpeta: '10_ENTREGA', nombre: 'Entrega', etapa: 'blanca',
      subetapas: ['Limpieza Final', 'Revisión', 'Registro Final'] },
  ],
  mapeoCapitulos: [
    { cap: '1.) Preliminares', etapa: '01_PRELIMINARES', nota: 'Cerramiento provisional, descapote, recebado y compactación, replanteo, campamento e instalaciones provisionales agregados como subcarpetas.' },
    { cap: '2.) Estructura en concreto', etapa: '02_EXCAVACIONES + 03_CIMENTACION + 04_ESTRUCTURA', nota: 'El presupuesto agrupa zapatas, vigas de cimentación, placa de contrapiso, columnas, entrepisos, escaleras y vigas de cubierta en un solo capítulo; en obra se separan por etapa y por piso.' },
    { cap: '3.) Cubierta', etapa: '07_CUBIERTA', nota: 'Corresponde directo.' },
    { cap: '4.) Mampostería', etapa: '05_MAMPOSTERIA', nota: 'Corresponde directo.' },
    { cap: '5.) Inst. Eléctricas', etapa: '06_INSTALACIONES / Eléctricas', nota: 'Corresponde directo.' },
    { cap: '6.) Inst. Hidro-Sanitarias', etapa: '06_INSTALACIONES / Hidráulicas y Sanitarias', nota: 'Corresponde directo.' },
    { cap: '7.) Pañete', etapa: '08_ACABADOS / Pañetes', nota: 'Corresponde directo.' },
    { cap: '8.) Enchapes', etapa: '08_ACABADOS / Enchapes', nota: 'Corresponde directo.' },
    { cap: '9.) Estuco', etapa: '08_ACABADOS / Estuco', nota: 'Subcarpeta agregada (no existía en la versión original de ETAPAS OBRA).' },
    { cap: '10.) Carpintería Metálica', etapa: '08_ACABADOS / Carpintería y Herrería', nota: 'Corresponde directo.' },
    { cap: '11.) Pintura', etapa: '08_ACABADOS / Pintura', nota: 'Corresponde directo.' },
    { cap: '12.) Aparatos Hidrosanitarios', etapa: '08_ACABADOS / Aparatos Hidrosanitarios', nota: 'Subcarpeta agregada.' },
    { cap: '13.) Mueble Cocina', etapa: '08_ACABADOS / Mueble Cocina', nota: 'Subcarpeta agregada.' },
    { cap: '14.) Armarios', etapa: '08_ACABADOS / Armarios', nota: 'Subcarpeta agregada.' },
    { cap: '15.) Mano de Obra', etapa: '(transversal)', nota: 'Costo de mano de obra general por m², no es una etapa física, aplica a todas las etapas. No se crea carpeta.' },
    { cap: '16) Exterior', etapa: '09_EXTERIORES / Zonas Exteriores', nota: 'Corresponde directo (zona dura exterior).' },
    { cap: '17.) Cerramiento', etapa: '09_EXTERIORES / Cerramiento Definitivo', nota: 'Cerramiento definitivo en mampostería, reja y portón; distinto del cerramiento provisional del capítulo 1.' },
  ],
};
